# Cloudflare Pages configuration for OpenKey Demo
name = "openkey-demo"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".svelte-kit/cloudflare"

[vars]
# These can be overridden in Cloudflare dashboard
# VITE_OPENKEY_HOST = "http://localhost:3001"
VITE_OPENKEY_HOST = "https://api.openkey.so"
VITE_CLIENT_ID = "ok_ecee4fd7667c1370c44eae3922558f3b"
